import { Empresa } from './empresa.class';
import { Banco } from './banco.class';
import { CodigoPostal } from './codigoPostal.class';
import { NominaCatalogo } from './nominaCatalogo.class';
import { DatoFiscal } from './datoFiscal.class';

export class Trabajador {
    idTrabajador: number;
    nombre: string;
    apellidoPaterno: string;
    apellidoMaterno: string;
    email: string;
    departamento: string;
    puesto: string;
    calle: string;
    numExt: string;
    numInt: string;
    referencia: string;
    codigoPostal: CodigoPostal;
    titulo: string;
    telefonoFijo: string;
    telefonoExt: string;
    telefonoMovil: string;
    asimilado: boolean;
    datoFiscal: DatoFiscal;
    numSeguridadSocial: string;
    fechaInicioRelLaboral: Date;
    antiguedad: string;
    contrato: NominaCatalogo;
    sindicalizado: boolean;
    jornada: NominaCatalogo;
    numEmpleado: string;
    riesgoPuesto: NominaCatalogo;
    periodicidadPago: NominaCatalogo;
    banco: Banco;
    tipoCuentaBancaria: string;
    cuentaBancaria: string;
    salarioBaseCotApor: number;
    salarioDiarioIntegrado: number;
    activo: boolean;
    empresaSalarios: Empresa;
    empresaAsimilados: Empresa;
    constructor() {
        this.idTrabajador = 0;
        this.nombre = null;
        this.apellidoPaterno = null;
        this.apellidoMaterno = null;
        this.email = null;
        this.departamento = null;
        this.puesto = null;
        this.calle = null;
        this.numExt = null;
        this.numInt = null;
        this.referencia = null;
        this.codigoPostal = new CodigoPostal();
        this.titulo = null;
        this.telefonoFijo = null;
        this.telefonoExt = null;
        this.telefonoMovil = null;
        this.asimilado = false;
        this.datoFiscal = new DatoFiscal();
        this.numSeguridadSocial = null;
        this.fechaInicioRelLaboral = new Date();
        this.antiguedad = null;
        this.contrato = new NominaCatalogo();
        this.sindicalizado = false;
        this.jornada = new NominaCatalogo();
        this.numEmpleado = null;
        this.riesgoPuesto = new NominaCatalogo();
        this.periodicidadPago = new NominaCatalogo();
        this.banco = new Banco();
        this.tipoCuentaBancaria = null;
        this.cuentaBancaria = null;
        this.salarioBaseCotApor = 0.0;
        this.salarioDiarioIntegrado = 0.0;
        this.activo = true;
        this.empresaSalarios = new Empresa();
        this.empresaAsimilados = new Empresa();
    }
}
